// Code generated by MockGen. DO NOT EDIT.
// Source: client/listers/policy/v1alpha1/clustervalidatepolicy.go

// Package mock is a generated GoMock package.
package mock

import (
	"reflect"

	"github.com/golang/mock/gomock"
	"k8s.io/apimachinery/pkg/labels"

	"github.com/k-cloud-labs/pkg/apis/policy/v1alpha1"
)

// MockClusterValidatePolicyLister is a mock of ClusterValidatePolicyLister interface.
type MockClusterValidatePolicyLister struct {
	ctrl     *gomock.Controller
	recorder *MockClusterValidatePolicyListerMockRecorder
}

// MockClusterValidatePolicyListerMockRecorder is the mock recorder for MockClusterValidatePolicyLister.
type MockClusterValidatePolicyListerMockRecorder struct {
	mock *MockClusterValidatePolicyLister
}

// NewMockClusterValidatePolicyLister creates a new mock instance.
func NewMockClusterValidatePolicyLister(ctrl *gomock.Controller) *MockClusterValidatePolicyLister {
	mock := &MockClusterValidatePolicyLister{ctrl: ctrl}
	mock.recorder = &MockClusterValidatePolicyListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterValidatePolicyLister) EXPECT() *MockClusterValidatePolicyListerMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockClusterValidatePolicyLister) Get(name string) (*v1alpha1.ClusterValidatePolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", name)
	ret0, _ := ret[0].(*v1alpha1.ClusterValidatePolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockClusterValidatePolicyListerMockRecorder) Get(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClusterValidatePolicyLister)(nil).Get), name)
}

// List mocks base method.
func (m *MockClusterValidatePolicyLister) List(selector labels.Selector) ([]*v1alpha1.ClusterValidatePolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", selector)
	ret0, _ := ret[0].([]*v1alpha1.ClusterValidatePolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockClusterValidatePolicyListerMockRecorder) List(selector interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockClusterValidatePolicyLister)(nil).List), selector)
}
