/*
Copyright 2022 by k-cloud-labs org.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/k-cloud-labs/pkg/apis/policy/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterValidatePolicies implements ClusterValidatePolicyInterface
type FakeClusterValidatePolicies struct {
	Fake *FakePolicyV1alpha1
}

var clustervalidatepoliciesResource = schema.GroupVersionResource{Group: "policy.kcloudlabs.io", Version: "v1alpha1", Resource: "clustervalidatepolicies"}

var clustervalidatepoliciesKind = schema.GroupVersionKind{Group: "policy.kcloudlabs.io", Version: "v1alpha1", Kind: "ClusterValidatePolicy"}

// Get takes name of the clusterValidatePolicy, and returns the corresponding clusterValidatePolicy object, and an error if there is any.
func (c *FakeClusterValidatePolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterValidatePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clustervalidatepoliciesResource, name), &v1alpha1.ClusterValidatePolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterValidatePolicy), err
}

// List takes label and field selectors, and returns the list of ClusterValidatePolicies that match those selectors.
func (c *FakeClusterValidatePolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterValidatePolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clustervalidatepoliciesResource, clustervalidatepoliciesKind, opts), &v1alpha1.ClusterValidatePolicyList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterValidatePolicyList{ListMeta: obj.(*v1alpha1.ClusterValidatePolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterValidatePolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterValidatePolicies.
func (c *FakeClusterValidatePolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clustervalidatepoliciesResource, opts))
}

// Create takes the representation of a clusterValidatePolicy and creates it.  Returns the server's representation of the clusterValidatePolicy, and an error, if there is any.
func (c *FakeClusterValidatePolicies) Create(ctx context.Context, clusterValidatePolicy *v1alpha1.ClusterValidatePolicy, opts v1.CreateOptions) (result *v1alpha1.ClusterValidatePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clustervalidatepoliciesResource, clusterValidatePolicy), &v1alpha1.ClusterValidatePolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterValidatePolicy), err
}

// Update takes the representation of a clusterValidatePolicy and updates it. Returns the server's representation of the clusterValidatePolicy, and an error, if there is any.
func (c *FakeClusterValidatePolicies) Update(ctx context.Context, clusterValidatePolicy *v1alpha1.ClusterValidatePolicy, opts v1.UpdateOptions) (result *v1alpha1.ClusterValidatePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clustervalidatepoliciesResource, clusterValidatePolicy), &v1alpha1.ClusterValidatePolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterValidatePolicy), err
}

// Delete takes name of the clusterValidatePolicy and deletes it. Returns an error if one occurs.
func (c *FakeClusterValidatePolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(clustervalidatepoliciesResource, name, opts), &v1alpha1.ClusterValidatePolicy{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterValidatePolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clustervalidatepoliciesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterValidatePolicyList{})
	return err
}

// Patch applies the patch and returns the patched clusterValidatePolicy.
func (c *FakeClusterValidatePolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterValidatePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clustervalidatepoliciesResource, name, pt, data, subresources...), &v1alpha1.ClusterValidatePolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterValidatePolicy), err
}
